### ISSUE TITLE
[>1.6.0.1] Error: Match error: Failed Match.Where validation in field collection

### ISSUE THREAD

**Issue by nadeemja** [Meteor-Community-Packages/denormalize#14]
Hi,

In any Meteor version above, but not including 1.6.0.1, I'm getting this error:

https://pastebin.com/raw/CP9Dgep8

Here are the contents of my versions file after updating to 1.7.0.3:

> accounts-base@1.4.2
> accounts-password@1.5.1
> aldeed:autoform@5.8.1
> aldeed:autoform-bs-button-group-input@1.0.3
> aldeed:collection2@2.10.0
> aldeed:collection2-core@1.2.0
> aldeed:console-helpers@0.0.1
> aldeed:schema-deny@1.1.0
> aldeed:schema-index@1.1.1
> aldeed:simple-schema@1.5.3
> allow-deny@1.1.0
> autoupdate@1.4.0
> babel-compiler@7.1.1
> babel-runtime@1.2.2
> babrahams:editable-text@0.9.7
> base64@1.0.11
> binary-heap@1.0.10
> blaze@2.3.2
> blaze-html-templates@1.1.2
> blaze-tools@1.0.10
> boilerplate-generator@1.5.0
> bredikhin:contact-form@1.0.1
> caching-compiler@1.1.12
> caching-html-compiler@1.1.2
> callback-hook@1.1.0
> cfs:http-methods@0.0.32
> check@1.3.1
> chuangbo:cookie@1.1.0
> coffeescript@1.0.17
> cultofcoders:grapher@1.3.1
> cultofcoders:publish-composite@1.5.1
> cultofcoders:redis-oplog@1.2.6
> daoli:highcharts@5.0.7-rc3
> dburles:collection-helpers@1.1.0
> dburles:mongo-collection-instances@0.3.5
> ddp@1.4.0
> ddp-client@2.3.2
> ddp-common@1.4.0
> ddp-rate-limiter@1.0.7
> ddp-server@2.2.0
> deps@1.0.12
> diff-sequence@1.1.0
> disable-oplog@1.0.7
> drewy:autoform-datetimepicker@1.0.666666
> drewy:datetimepicker@1.0.3
> dynamic-import@0.4.0
> east5th:check-checker@0.2.1
> east5th:package-scan@0.0.5
> ecmascript@0.11.1
> ecmascript-runtime@0.7.0
> ecmascript-runtime-client@0.7.1
> ecmascript-runtime-server@0.7.0
> ejson@1.1.0
> email@1.2.3
> es5-shim@4.8.0
> force-ssl@1.1.0
> force-ssl-common@1.1.0
> fortawesome:fontawesome@4.7.0
> francocatena:status@1.5.3
> geojson-utils@1.0.10
> gwendall:body-events@0.1.6
> herteby:denormalize@0.6.5
> hot-code-push@1.0.4
> html-tools@1.0.11
> htmljs@1.0.11
> http@1.4.1
> id-map@1.1.0
> jperl:match-ex@1.0.0
> jquery@1.11.10
> juliancwirko:s-alert@3.2.0
> juliancwirko:s-alert-genie@3.1.3
> kadira:blaze-layout@2.3.0
> lai:collection-extensions@0.2.1_1
> launch-screen@1.1.1
> less@2.7.12
> livedata@1.0.18
> localstorage@1.2.0
> logging@1.1.20
> matb33:collection-hooks@0.8.4
> mdg:validation-error@0.2.0
> meteor@1.9.0
> meteor-base@1.4.0
> meteor-candy@1.0.0
> meteorhacks:cluster@1.6.9
> meteorhacks:meteorx@1.4.1
> meteorhacks:picker@1.0.3
> meteorspark:util@0.2.0
> meteortoys:allthings@4.0.0
> meteortoys:authenticate@4.0.0
> meteortoys:autopub@4.0.0
> meteortoys:blueprint@4.0.0
> meteortoys:email@4.0.0
> meteortoys:hotreload@4.0.0
> meteortoys:listen@4.0.0
> meteortoys:method@4.0.0
> meteortoys:mobile@4.0.0
> meteortoys:pub@4.0.0
> meteortoys:result@4.0.0
> meteortoys:shell@4.0.0
> meteortoys:status@4.0.0
> meteortoys:sub@4.0.0
> meteortoys:throttle@4.0.0
> meteortoys:toggle@4.0.0
> meteortoys:toykit@4.0.1
> minifier-css@1.3.1
> minifier-js@2.3.5
> minimongo@1.4.4
> mobile-experience@1.0.5
> mobile-status-bar@1.0.14
> modern-browsers@0.1.2
> modules@0.12.0
> modules-runtime@0.10.0
> momentjs:moment@2.18.1
> mongo@1.5.0
> mongo-dev-server@1.1.0
> mongo-id@1.0.7
> mrt:jquery-imagesloaded@0.0.2
> msavin:jetsetter@4.0.0
> msavin:mongol@4.0.1
> nadeemjq:accounts-passwordless@0.2.5
> nadeemjq:isotope@1.0.14
> npm-bcrypt@0.9.3
> npm-mongo@3.0.11
> observe-sequence@1.0.16
> ogourment:settings@1.0.1
> ongoworks:security@2.1.0
> ordered-dict@1.1.0
> ostrio:flow-router-extra@3.4.3
> percolate:migrations@1.0.2
> percolate:synced-cron@1.3.2
> promise@0.11.1
> raix:eventemitter@0.1.3
> random@1.1.0
> rate-limit@1.0.9
> reactive-dict@1.2.0
> reactive-var@1.0.11
> reload@1.2.0
> retry@1.1.0
> reywood:publish-composite@1.5.2
> routepolicy@1.0.13
> rzymek:fullcalendar@3.4.0
> sacha:spin@2.3.1
> service-configuration@1.0.11
> session@1.1.7
> sha@1.0.9
> shell-server@0.3.1
> simple:reactive-method@1.0.2
> socket-stream-client@0.2.2
> softwarerero:accounts-t9n@1.3.11
> spacebars@1.0.15
> spacebars-compiler@1.1.3
> srp@1.0.10
> standard-minifier-css@1.4.1
> standard-minifier-js@2.3.4
> staringatlights:fast-render@2.16.5
> staringatlights:inject-data@2.0.5
> steffo:meteor-accounts-saml@0.0.13
> stylus@2.513.13
> supermongol@2.0.0
> tap:i18n@1.7.0
> templating@1.3.2
> templating-compiler@1.3.3
> templating-runtime@1.3.2
> templating-tools@1.1.2
> tracker@1.2.0
> ui@1.0.13
> underscore@1.0.10
> underscorestring:underscore.string@3.3.4
> url@1.2.0
> useraccounts:bootstrap@1.14.2
> useraccounts:core@1.14.2
> vazco:universe-selectize@0.1.23
> webapp@1.6.0
> webapp-hashing@1.0.9
> yagni:split-on-newlines@0.0.5
> zimme:collection-behaviours@1.1.3
> zimme:collection-timestampable@1.0.9

I'm seeing this on all version of Meteor after 1.6.0.1. Possibly related to Cult Of Coders packages, however upgrading them doesn't help. (@theodorDiaconu) 

What might be happening?

**Comment by nadeemja** [comment]
Btw, the collection field is referencing Meteor.users.

**Comment by StorytellerCZ** [comment]
Unless anyone else can confirm this is still happening I'm closing the issue as it has been a while and lot of changes since then.
