### ISSUE TITLE
upgrade matb33:collection-hooks dependency

### ISSUE THREAD

**Issue by copleykj** [Meteor-Community-Packages/denormalize#20]
This currently constrains the collection hooks package not to upgrade past 0.8.4 and the current version is 1.0.1. 

I'd be happy to submit a pull request if there is a chance it will get merged and published.

**Comment by copleykj** [comment]
Ping

**Comment by Herteby** [comment]
Not 100% if @-mentioning people in other threads means they get notified, so posting a link here too:
https://github.com/Herteby/denormalize/issues/21

**Comment by StorytellerCZ** [comment]
Done and published herteby:denormalize@0.6.6.
