### ISSUE TITLE
Handing over ownership of this package

### ISSUE THREAD

**Issue by Herteby** [Meteor-Community-Packages/denormalize#21]
@Floriferous @copleykj @doronrk

Hi! Sorry for taking so long to respond. I switched jobs about 2 years ago and haven't worked with Meteor since. I was wondering if any of you who are using the package would like to take over the ownership of it?

Maybe I should involve @theodorDiaconu as well, as Grapher is using this package.

**Comment by copleykj** [comment]
I'll see about proposing this for inclusion as a community-maintained package tomorrow.

**Comment by StorytellerCZ** [comment]
Thank you, the package is now part of MCP.
